import { STAGE_TEXTS } from "./texts.js?v=20260331-9";

const stage1Text = STAGE_TEXTS.stage1;

export const STAGES = [
  {
    id: "stage1",
    name: stage1Text.name,
    turnLimit: 5,
    assets: {
      intro: "assets/backgrounds/OP/oheya.png",
      background: "assets/backgrounds/stage1/right.png",
      leftBackground: "assets/backgrounds/stage1/left.png",
      rightBackground: "assets/backgrounds/stage1/right.png",
      player: "assets/characters/yuu-default.png",
      rival: "assets/characters/mizuka-default.png",
      playerPops: {
        idle: "assets/characters/yuu/yuu_idle.png",
        cheer: "assets/characters/yuu/yuu_cheer.png",
        love: "assets/characters/yuu/yuu_hug.png",
        rest: "assets/characters/yuu/yuu_rest.png",
        gift: "assets/characters/yuu/yuu_present.png",
      },
      rivalPops: {
        idle: "assets/characters/zuika/zuika_idle.png",
        cheer: "assets/characters/zuika/zuika_cheer.png",
        love: "assets/characters/zuika/zuika_hug.png",
        rest: "assets/characters/zuika/zuika_rest.png",
        gift: "assets/characters/zuika/zuika_present.png",
      },
      fightSprites: {
        stance: "assets/characters/zuika/fight/stance.png",
        jab: "assets/characters/zuika/fight/jab.png",
        straight: "assets/characters/zuika/fight/straight.png",
        uppercut1: "assets/characters/zuika/fight/uppercut_1.png",
        uppercut2: "assets/characters/zuika/fight/uppercut_2.png",
      },
      fightSequence: [
        { key: "stance", duration: 520 },
        { key: "jab", duration: 220 },
        { key: "stance", duration: 420 },
        { key: "uppercut1", duration: 190 },
        { key: "uppercut2", duration: 260 },
        { key: "stance", duration: 880 },
      ],
    },
    opening: {
      setup: {
        background: "assets/backgrounds/OP/arena.png",
        leftName: "Zuika",
        rightName: "Champion",
        leftSprite: "assets/characters/zuika/fight/stance.png",
        rightSprite: "assets/characters/champion/fight/stance_fatigue.png",
        leftHpMax: 100,
        rightHpMax: 100,
        leftHpInitial: 100,
        rightHpInitial: 54,
      },
      openingText: stage1Text.opening,
      steps: [
        { type: "showMatchTitle", duration: 2100 },
        { type: "wait", duration: 700 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/jab.png" },
        { type: "wait", duration: 120 },
        { type: "damage", target: "right", amount: 8, x: "72%", y: "38%" },
        { type: "wait", duration: 220 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "wait", duration: 360 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/straight.png" },
        { type: "wait", duration: 110 },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/straight_damage.png" },
        { type: "damage", target: "right", amount: 12, x: "76%", y: "35%" },
        { type: "wait", duration: 260 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/stance_fatigue.png" },
        { type: "wait", duration: 380 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 120 },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/body_damage.png" },
        { type: "damage", target: "right", amount: 14, x: "74%", y: "49%" },
        { type: "wait", duration: 260 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/stance_fatigue.png" },
        { type: "wait", duration: 420 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_1.png" },
        { type: "wait", duration: 240 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_2.png" },
        { type: "wait", duration: 70 },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/uppercut_damage1.png" },
        { type: "damage", target: "right", amount: 20, x: "78%", y: "27%" },
        { type: "mouthpiece", x: "74%", y: "34%" },
        { type: "wait", duration: 130 },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/uppercut_damage2.png" },
        { type: "wait", duration: 150 },
        { type: "updateSprite", target: "right", src: "assets/characters/champion/fight/uppercut_damage3.png" },
        { type: "wait", duration: 500 },
        { type: "showKO" },
        { type: "wait", duration: 1700 },
        { type: "showChampionScene", duration: 2800 },
        { type: "showNarration", duration: 3200 },
        { type: "showIntroScene" },
      ],
    },
    victorySequence: {
      setup: {
        background: "assets/backgrounds/OP/arena.png",
        leftName: "Zuika",
        rightName: "Gyaru",
        leftSprite: "assets/characters/zuika/fight/stance.png",
        rightSprite: "assets/characters/gyaru/stance_fatigue.png",
        leftHpMax: 100,
        rightHpMax: 100,
        leftHpInitial: 100,
        rightHpInitial: 100,
      },
      steps: [
        { type: "wait", duration: 700 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/jab.png" },
        { type: "wait", duration: 120 },
        { type: "damage", target: "right", amount: 12, x: "76%", y: "36%" },
        { type: "wait", duration: 240 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/jab.png" },
        { type: "wait", duration: 260 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_fatigue.png" },
        { type: "wait", duration: 300 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/jab.png" },
        { type: "wait", duration: 100 },
        { type: "damage", target: "right", amount: 18, x: "77%", y: "35%" },
        { type: "wait", duration: 140 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/straight.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/straight_damage.png" },
        { type: "wait", duration: 120 },
        { type: "damage", target: "right", amount: 20, x: "79%", y: "34%" },
        { type: "wait", duration: 220 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_fatigue.png" },
        { type: "wait", duration: 320 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 120 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/body_damage.png" },
        { type: "damage", target: "right", amount: 20, x: "76%", y: "50%" },
        { type: "wait", duration: 260 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_1.png" },
        { type: "wait", duration: 220 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_2.png" },
        { type: "wait", duration: 80 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/uppercut_damage1.png" },
        { type: "damage", target: "right", amount: 30, x: "79%", y: "27%" },
        { type: "mouthpiece", x: "75%", y: "34%", color: "white" },
        { type: "wait", duration: 120 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/uppercut_damage2.png" },
        { type: "wait", duration: 120 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/uppercut_damage3.png" },
        { type: "wait", duration: 500 },
        { type: "showKO" },
      ],
    },
    yarisugiSequence: {
      setup: {
        background: "assets/backgrounds/OP/arena.png",
        leftName: "Zuika",
        rightName: "Gyaru",
        leftSprite: "assets/characters/zuika/fight/stance.png",
        rightSprite: "assets/characters/gyaru/stance_fatigue.png",
        leftHpMax: 100,
        rightHpMax: 100,
        leftHpInitial: 100,
        rightHpInitial: 100,
      },
      steps: [
        { type: "wait", duration: 700 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/jab.png" },
        { type: "wait", duration: 120 },
        { type: "damage", target: "right", amount: 20, x: "76%", y: "36%" },
        { type: "wait", duration: 240 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/jab.png" },
        { type: "wait", duration: 260 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_fatigue.png" },
        { type: "wait", duration: 300 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/straight.png" },
        { type: "wait", duration: 120 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/straight_damage.png" },
        { type: "damage", target: "right", amount: 30, x: "79%", y: "34%" },
        { type: "wait", duration: 240 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_fatigue.png" },
        { type: "wait", duration: 320 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_1.png" },
        { type: "wait", duration: 220 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/uppercut_2.png" },
        { type: "wait", duration: 80 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/uppercut_damage1.png" },
        { type: "damage", target: "right", amount: 50, x: "77%", y: "31%" },
        { type: "wait", duration: 800 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_bodydamage.png" },
        { type: "wait", duration: 300 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 100 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/body_damage.png" },
        { type: "shakeScreen", duration: 400 },
        { type: "damage", target: "right", amount: 15, x: "76%", y: "50%", noHpLoss: true },
        { type: "wait", duration: 180 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_bodydamage.png" },
        { type: "wait", duration: 200 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 100 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/body_damage.png" },
        { type: "shakeScreen", duration: 400 },
        { type: "damage", target: "right", amount: 18, x: "78%", y: "48%", noHpLoss: true },
        { type: "wait", duration: 180 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_bodydamage.png" },
        { type: "wait", duration: 200 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 100 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/body_damage.png" },
        { type: "shakeScreen", duration: 400 },
        { type: "damage", target: "right", amount: 20, x: "80%", y: "52%", noHpLoss: true },
        { type: "wait", duration: 300 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/stance.png" },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/stance_bodydamage.png" },
        { type: "wait", duration: 1200 },
        { type: "updateSprite", target: "left", src: "assets/characters/zuika/fight/body.png" },
        { type: "wait", duration: 80 },
        { type: "updateSprite", target: "right", src: "assets/characters/gyaru/body_damage.png" },
        { type: "impactSprite", target: "right", motion: "lift-left-down" },
        { type: "shakeScreen", duration: 460 },
        { type: "damage", target: "right", amount: 50, x: "77%", y: "50%", noHpLoss: true },
        { type: "mouthpiece", x: "74%", y: "38%", color: "white", direction: "left-down" },
        { type: "wait", duration: 800 },
        { type: "blackout", duration: 2000 },
        { type: "wait", duration: 1000 },
      ],
    },
    introLines: stage1Text.introLines,
    uiText: stage1Text.ui,
    initialStats: {
      playerHealth: 4,
      playerSpirit: 3,
      rivalLove: 5,
      rivalMotivation: 4,
    },
    endings: {
      care: {
        id: "care",
        title: stage1Text.endings.care.title,
        galleryId: "ending-care",
        image: "assets/gallery/kanbyou.png",
        description: stage1Text.endings.care.description,
      },
      boycott: {
        id: "boycott",
        title: stage1Text.endings.boycott.title,
        galleryId: "ending-boycott",
        image: "assets/gallery/boikot.png",
        description: stage1Text.endings.boycott.description,
      },
      obsession: {
        id: "obsession",
        title: stage1Text.endings.obsession.title,
        galleryId: "ending-obsession",
        image: "assets/gallery/sukisuki.png",
        description: stage1Text.endings.obsession.description,
      },
      foul: {
        id: "foul",
        title: stage1Text.endings.foul.title,
        galleryId: "ending-foul",
        image: "assets/gallery/yarisugi.png",
        description: stage1Text.endings.foul.description,
      },
      victory: {
        id: "victory",
        title: stage1Text.endings.victory.title,
        galleryId: "ending-win",
        image: "assets/gallery/trueend.png",
        description: stage1Text.endings.victory.description,
        victoryFlavor: stage1Text.endings.victory.victoryFlavor,
      },
    },
  },
];
